# Generated by Django 5.2.2 on 2025-06-09 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=255, verbose_name='Фамилия автора')),
                ('name', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('otc', models.CharField(max_length=255, verbose_name='Отчество автора')),
                ('phone', models.CharField(max_length=255, verbose_name='Отчество автора')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'авторы',
            },
        ),
    ]
