# Generated by Django 5.2.2 on 2025-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон автора'),
        ),
    ]
