# Generated by Django 5.2.2 on 2025-06-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0002_alter_author_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0, null=True, verbose_name='Широта перевала')),
                ('longitude', models.FloatField(default=0.0, null=True, verbose_name='Долгота перевала')),
                ('height', models.IntegerField(default=0, null=True, verbose_name='Высота перевала')),
            ],
            options={
                'verbose_name': 'Координаты перевала',
                'verbose_name_plural': 'Координаты перевалов',
            },
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(default=0, verbose_name='Номер родителя')),
                ('title', models.TextField(verbose_name='Название территории')),
            ],
            options={
                'verbose_name': 'Территория перевала',
                'verbose_name_plural': 'Территории перевалов',
            },
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=255, verbose_name='Красивое название')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Другое название')),
                ('connect', models.CharField(blank=True, default='', max_length=255, verbose_name='Соединение')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('level_winter', models.CharField(blank=True, default='', max_length=255, verbose_name='Уровень зимой')),
                ('level_summer', models.CharField(blank=True, default='', max_length=255, verbose_name='Уровень летом')),
                ('level_autumn', models.CharField(blank=True, default='', max_length=255, verbose_name='Уровень осенью')),
                ('level_spring', models.CharField(blank=True, default='', max_length=255, verbose_name='Уровень весной')),
                ('status', models.CharField(blank=True, choices=[('new', 'Новый'), ('pending', 'В работе'), ('accepted', 'Успешно'), ('rejected', 'Отказано')], default='new', verbose_name='Статус')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='perevalapp.coords', verbose_name='Координаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='perevalapp.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('title', models.TextField(verbose_name='Название изображения')),
                ('pereval', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='perevalapp.perevaladded', verbose_name='Перевал')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
