# Generated by Django 5.2.2 on 2025-06-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0003_coords_perevalareas_perevaladded_perevalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='coords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='perevalapp.coords', verbose_name='Координаты'),
        ),
    ]
