# Generated by Django 5.2.2 on 2025-06-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0004_alter_perevaladded_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaladded',
            name='coords',
        ),
    ]
