# Generated by Django 5.2.2 on 2025-06-11 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0005_remove_perevaladded_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='pereval',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='perevalapp.perevaladded', verbose_name='Перевал'),
        ),
    ]
