# Generated by Django 5.2.2 on 2025-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0006_coords_pereval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimage',
            name='images',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Изображение'),
        ),
    ]
