# Generated by Django 5.2.2 on 2025-06-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0007_alter_perevalimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimage',
            name='images',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
    ]
